name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: This is the workflow name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "AD"

